#define OPT7_A			A			// A
#define OPT7_B			T			// B
#define OPT7_C			M			// C
#define OPT7_D			U			// D
#define OPT7_E			D			// E
#define OPT7_F			Y			// F
#define OPT7_G			DOT			// G
#define OPT7_H			COMMA		// H
#define OPT7_I			S			// I
#define OPT7_J			BSLH		// J
#define OPT7_K			B			// K
#define OPT7_L			I			// L
#define OPT7_M			H			// M
#define OPT7_N			K			// N
#define OPT7_O			E			// O
#define OPT7_P			O			// P
#define OPT7_Q			SQT			// Q
#define OPT7_R			SEMI		// R
#define OPT7_S			J			// S
#define OPT7_T			L			// T
#define OPT7_U			F			// U
#define OPT7_V			N			// V
#define OPT7_W			R			// W
#define OPT7_X			FSLH		// X
#define OPT7_Y			W			// Y
#define OPT7_Z			Z			// Z
#define OPT7_A_GRV		Q			// À
#define OPT7_E_GRV		NON_US_BSLH	// È
#define OPT7_E_AIG		C			// É
#define OPT7_E_CIRC		LBKT		// Ê
#define OPT7_COMMA		G			// ,
#define OPT7_DOT		V			// .
#define OPT7_DQUOTE		X			// "
#define OPT7_QUOTE		P			// ’
