manifest:
    remotes:
        - name: refil
          url-base: https://github.com/refil
        - name: zmkfirmware
          url-base: https://github.com/zmkfirmware
    projects:
        - name: zmk
          remote: refil
          revision: adv360-beta
          import: app/west.yml
    self:
        path: config
